Repository KB-MoneyLog/money-log-FE, pull requests merged in 2025-04, with the labels that each got.

#7 :sparkles: FEAT: 대시보드 수입 지출 분석 기능 추가
  money-log/src/components/GoalTracker.vue
  money-log/src/components/IEComparing.vue
  money-log/src/components/MostSpent.vue
Labels: feat

#11 ✨ FEAT: 모달 창 구현
  money-log/src/App.vue
  money-log/src/assets/coin-icon.png
  money-log/src/components/FloatingButton.vue
  money-log/src/components/MoneyInputModal.vue
Labels: feat

#15 ✨ FEAT: 대시보드 캘린더 구현 완료
  money-log/db.json
  money-log/src/assets/main.css
  money-log/src/components/Calender.vue
  money-log/src/components/Footer.vue
  money-log/src/components/Header.vue
  money-log/src/main.js
  money-log/src/router/index.js
  money-log/src/stores/transactionStore.js
  money-log/src/stores/users.js
  money-log/src/views/DashBoard.vue
Labels: feat

#16 :memo: COMMENT: 컴포넌트에 주석 추가
  money-log/src/components/MoneyInputModal.vue
Labels: docs

#17 :sparkles: FEAT: 대시보드 수입 지출 분석 기능 디벨롭
  money-log/src/components/GoalTracker.vue
  money-log/src/components/IEComparing.vue
  money-log/src/components/MostSpent.vue
Labels: feat

#19 🚚 RENAME: 거래 내역 리스트 관련 페이지 생성
  money-log/src/components/FilterBar.vue
  money-log/src/router/index.js
  money-log/src/views/TransactionList.vue
Labels: docs

#22 :sparkles: FEAT: 수입/지출 카테고리 항목 DB화, 추가 작업
  money-log/db.json
  money-log/src/assets/coin-icon.png
  money-log/src/assets/coin-icon.svg
  money-log/src/components/MoneyInputModal.vue
Labels: docs, refactor

#24 :sparkles: FEAT: 리스트페이지 필터링 바 구현
  money-log/src/components/ListFilter.vue
  money-log/src/views/TransactionList.vue
Labels: feat

#25 ✨ FEAT: 마이페이지 UI 구현 완료
  money-log/db.json
  money-log/src/assets/main.css
  money-log/src/assets/money.svg
  money-log/src/assets/mypage-background.png
  money-log/src/assets/shopping.svg
  money-log/src/assets/trophy.svg
  money-log/src/components/MoneyLog.vue
  money-log/src/router/index.js
  money-log/src/views/Mypage.vue
Labels: feat

#26 ✨ FEAT: 마이페이지 데이터 바인딩 및 거래 내역 store 수정
  money-log/db.json
  money-log/src/components/Calender.vue
  money-log/src/components/Header.vue
  money-log/src/components/MoneyLog.vue
  money-log/src/stores/goal.js
  money-log/src/stores/transactionStore.js
  money-log/src/views/Mypage.vue
Labels: duplicate, feat

#29 ✨ FEATURE: 입력모달에서 저장 버튼 누를 시, db에 새로운 항목 추가 기능 구현
  money-log/db.json
  money-log/src/App.vue
  money-log/src/components/FloatingButton.vue
  money-log/src/components/MoneyInputModal.vue
Labels: feat

#31 :art: DESIGN: 대시보드 소비 카테고리 영역 디자인
  money-log/src/components/MostSpent.vue
  money-log/src/views/DashBoard.vue
Labels: refactor

#33 :bug: FIX: db.json 내 id들이 큰따옴표 안으로 옮겨진 버그 수리
  money-log/db.json
Labels: bug

#35 “:bug: FIX: 목표금액 비교 부분 소비 금액 불일치 오류 해결
  money-log/src/components/GoalTracker.vue
Labels: bug

#39 🐛 FIX: 4월 9일 구현 내용 에러 수정
  money-log/db.json
  money-log/src/components/GoalTracker.vue
  money-log/src/components/IEComparing.vue
  money-log/src/components/MoneyInputModal.vue
  money-log/src/components/MoneyLog.vue
  money-log/src/components/MostSpent.vue
  money-log/src/stores/goal.js
  money-log/src/stores/transactionStore.js
  money-log/src/stores/users.js
Labels: bug

#41 :art: DESIGN 상세페이지 CSS 수정
  money-log/src/components/DetailBackground.vue
  money-log/src/components/DetailCenter.vue
Labels: feat

#44 ✨ FEAT: 리스트 페이지 레이아웃 구성 및 라우팅 추가
  money-log/src/assets/main.css
  money-log/src/views/TransactionList.vue
Labels: feat

#50 :art: DESIGN: 대시보드 골트래커 디자인
  money-log/package-lock.json
  money-log/package.json
  money-log/src/components/DonutChart.vue
  money-log/src/components/GoalTracker.vue
Labels: feat

#52 [ ✨ FEAT ] 마이페이지 목표금액 설정, 개인정보 수정 기능
  money-log/src/views/Mypage.vue
Labels: feat

#53 :sparkles: FEAT: 월별 거래 내역 데이터 바인딩 구현 완료
  money-log/db.json
  money-log/src/stores/transactionStore.js
  money-log/src/views/TransactionList.vue
Labels: feat

#54 :art: DESIGN: 대시보드 수입 지출 비교 영역 디자인
  money-log/src/components/IEComparing.vue
Labels: feat

#61 :art: DESIGN: 대시보드 캘린더 영역 UI 디자인
  money-log/src/components/Calender.vue
Labels: feat

#62 “:bug: FIX: 목표금액 비교 부분 오류 해결
  money-log/src/components/DonutChart.vue
  money-log/src/components/GoalTracker.vue
Labels: bug

#64 ✨ FEAT: 거래 내역 리스트 필터링 구현
  money-log/src/components/ListFilter.vue
  money-log/src/stores/categoryIcons.js
  money-log/src/stores/transactionStore.js
  money-log/src/views/TransactionList.vue
Labels: feat, refactor

#65 :art: DESIGN: 상세 내역 페이지 버튼 생성
  money-log/src/components/DetailCenter.vue
  money-log/src/views/TransactionDetail.vue
Labels: bug, feat

#66 :art: DESIGN: 대시보드 전체 UI 디자인 수정
  money-log/src/components/Footer.vue
  money-log/src/components/Header.vue
  money-log/src/views/DashBoard.vue
  money-log/src/views/TransactionList.vue
Labels: feat

#68 :art: DESIGN: 거래 내역 리스트 필터 인덱스 영역 간격 조정
  money-log/src/views/TransactionList.vue
Labels: feat

#69 :sparkles: FEATURE: 리스트 UI, 세부내역 기능 구현
  money-log/src/components/DetailCenter.vue
  money-log/src/components/MoneyEditModal.vue
  money-log/src/router/index.js
  money-log/src/views/TransactionDetail.vue
  money-log/src/views/TransactionList.vue
Labels: bug, feat

#70 ✨ FEAT: 거래내역 카테고리 필터링 구현
  money-log/db.json
  money-log/src/components/ListFilter.vue
  money-log/src/stores/categoryIcons.js
  money-log/src/stores/transactionStore.js
  money-log/src/views/TransactionList.vue
Labels: feat, refactor

#72 ✨ FEAT: 상세 페이지에서 삭제 기능 구현
  money-log/db.json
  money-log/src/App.vue
  money-log/src/components/DetailBackground.vue
  money-log/src/components/DetailCenter.vue
  money-log/src/components/Footer.vue
  money-log/src/components/Header.vue
  money-log/src/components/MoneyEditModal.vue
  money-log/src/components/MoneyInputModal.vue
  money-log/src/views/TransactionDetail.vue
Labels: feat

#73 ♻️ Refactor: db.json에 용돈 카테고리 이름 변경
  money-log/db.json
Labels: refactor

#75 ♻️ REFACTOR: v1.0 배포 전 마지막 점검
  money-log/src/components/Calender.vue
  money-log/src/components/DetailBackground.vue
  money-log/src/components/DetailCenter.vue
  money-log/src/components/FilterBar.vue
  money-log/src/components/Header.vue
  money-log/src/components/ListFilter.vue
  money-log/src/router/index.js
  money-log/src/views/DashBoard.vue
  money-log/src/views/TransactionDetail.vue
  money-log/src/views/TransactionList.vue
Labels: feat

#77 🚑 HOTFIX: 뒤로가기 했을 때 해당 월 리스트로 이동 안되는 에러 해결
  money-log/db.json
  money-log/src/components/DetailCenter.vue
Labels: bug

#80 🚑 HOTFIX: 푸터에서 리스트 페이지 이동 안 되는 에러 해결
  money-log/db.json
  money-log/src/components/Footer.vue
  money-log/src/router/index.js
Labels: bug

#82 ♻️ REFACTOR: 거래 내역 입력 모달창 composition API로 리팩토링
  money-log/db.json
  money-log/src/App.vue
  money-log/src/components/MoneyInputModal.vue
  money-log/src/views/TransactionList.vue
Labels: refactor
